# Generated by Django 5.0.1 on 2024-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_crud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("bd", "Bangladesh"), ("jp", "Japan"), ("us", "USA")],
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField()),
                ("birth_date", models.DateField()),
                ("hobbies", models.ManyToManyField(blank=True, to="app_crud.hobby")),
            ],
        ),
    ]
